# Generated by Django 5.1.7 on 2025-05-20 10:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Name/title of the shift', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the shift requirements', null=True)),
                ('location', models.TextField(help_text='Physical location where the shift will take place')),
                ('location_map_url', models.URLField(blank=True, help_text='URL to map of the location', null=True)),
                ('company_name', models.CharField(blank=True, help_text='Name of the company posting the shift', max_length=255, null=True)),
                ('start_time', models.TimeField(db_index=True, help_text='Scheduled start time of the shift')),
                ('end_time', models.TimeField(db_index=True, help_text='Scheduled end time of the shift')),
                ('base_pay', models.DecimalField(decimal_places=2, default=0.0, help_text='Base pay for the shift', max_digits=10)),
                ('bonus_pay', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional bonus pay for the shift', max_digits=10)),
                ('total_pay', models.DecimalField(decimal_places=2, default=0.0, help_text='Total payment for the shift', max_digits=10)),
                ('total_openings', models.PositiveIntegerField(default=1, help_text='Total number of workers needed for this shift')),
                ('filled_openings', models.PositiveIntegerField(default=0, help_text='Number of positions already filled')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('TAKEN', 'Taken'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING_APPROVAL', help_text='Current status of the shift', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('requirements', models.JSONField(blank=True, help_text='JSON array of required qualifications or items', null=True)),
                ('prohibited_items', models.JSONField(blank=True, help_text='JSON array of items not allowed during shift', null=True)),
                ('image_url', models.URLField(blank=True, help_text='URL of image associated with the shift', null=True)),
                ('employer', models.ForeignKey(help_text='User who created the shift', on_delete=django.db.models.deletion.CASCADE, related_name='created_shifts', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, help_text='Manager responsible for approving the shift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('TAKEN', 'Taken'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='TAKEN', help_text='Current status of the application', max_length=20)),
                ('employee', models.ForeignKey(help_text='Employee applying for the shift', on_delete=django.db.models.deletion.CASCADE, related_name='shift_applications', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(help_text='Shift being applied for', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='shift.shift')),
            ],
            options={
                'verbose_name': 'Shift Application',
                'verbose_name_plural': 'Shift Applications',
            },
        ),
        migrations.CreateModel(
            name='ShiftApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Approval decision status', max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Manager comments about the approval', null=True)),
                ('manager', models.ForeignKey(help_text='Manager responsible for approval', on_delete=django.db.models.deletion.CASCADE, related_name='shift_approvals', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(help_text='Shift being approved', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='shift.shift')),
            ],
            options={
                'verbose_name': 'Shift Approval',
                'verbose_name_plural': 'Shift Approvals',
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('actual_start_time', models.TimeField(blank=True, help_text='When the employee actually started working', null=True)),
                ('actual_end_time', models.TimeField(blank=True, help_text='When the employee actually finished working', null=True)),
                ('reminder_sent', models.BooleanField(default=False, help_text='send reminder notiies to employees')),
                ('completed_notes', models.TextField(blank=True, help_text='Notes about shift completion', null=True)),
                ('application', models.OneToOneField(blank=True, help_text='Original application that led to this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shift.shiftapplication')),
                ('employee', models.ForeignKey(help_text='Employee assigned to the shift', on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(help_text='Shift being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shift.shift')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('notification_type', models.CharField(choices=[('SHIFT_CREATED', 'Shift Created'), ('SHIFT_APPROVED', 'Shift Approved'), ('SHIFT_REJECTED', 'Shift Rejected'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('SHIFT_STARTING_SOON', 'Shift Starting Soon'), ('SHIFT_REMINDER', 'Shift Reminder')], help_text='Type of notification', max_length=50)),
                ('message', models.TextField(help_text='Content of the notification')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether the notification was sent via email')),
                ('push_sent', models.BooleanField(default=False, help_text='Whether the notification was sent via push notification')),
                ('user', models.ForeignKey(help_text='User receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_shift', models.ForeignKey(blank=True, help_text='Related shift if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='shift.shift')),
                ('related_application', models.ForeignKey(blank=True, help_text='Related application if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='shift.shiftapplication')),
                ('related_assignment', models.ForeignKey(blank=True, help_text='Related assignment if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='shift.shiftassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating score (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, help_text='Comments about the rating', null=True)),
                ('assignment', models.ForeignKey(help_text='Specific assignment being rated', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='shift.shiftassignment')),
                ('ratee', models.ForeignKey(help_text='User receiving the rating', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(help_text='User providing the rating', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(help_text='Shift being rated', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='shift.shift')),
            ],
            options={
                'verbose_name': 'Shift Rating',
                'verbose_name_plural': 'Shift Ratings',
            },
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['status', 'start_time'], name='shift_shift_status_19653e_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['employer', 'status'], name='shift_shift_employe_975de4_idx'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('filled_openings__lte', models.F('total_openings'))), name='filled_openings_lte_total'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftapplication',
            unique_together={('shift', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='shiftapproval',
            unique_together={('shift', 'manager')},
        ),
        migrations.AlterUniqueTogether(
            name='shiftrating',
            unique_together={('assignment', 'rater', 'ratee')},
        ),
    ]
