# Generated by Django 5.1.7 on 2025-05-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SHIFT_CREATED', 'Shift Created'), ('SHIFT_APPROVED', 'Shift Approved'), ('SHIFT_REJECTED', 'Shift Rejected'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('APPLICATION_CANCELLED', 'Application Cancelled'), ('SHIFT_STARTING_SOON', 'Shift Starting Soon'), ('SHIFT_REMINDER', 'Shift Reminder')], help_text='Type of notification', max_length=50),
        ),
    ]
