# Generated by Django 5.1.7 on 2025-05-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SHIFT_CREATED', 'Shift Created'), ('SHIFT_APPROVED', 'Shift Approved'), ('SHIFT_REJECTED', 'Shift Rejected'), ('SHIFT_TAKEN', 'Shift Taken'), ('SHIFT_CANCELLED', 'Shift Cancelled'), ('SHIFT_STARTING_SOON', 'Shift Starting Soon'), ('SHIFT_REMINDER', 'Shift Reminder')], help_text='Type of notification', max_length=50),
        ),
    ]
